/**
 * Cloudflare Worker entry for Panda Messages.
 *
 * Wraps the OpenNext-generated worker (`.open-next/worker.js`, produced by
 * `npx opennextjs-cloudflare build`) and adds the one thing it does not
 * ship: a `scheduled` handler, so the Cron Trigger in wrangler.toml
 * actually reaches the delivery engine.
 *
 * The cron tick calls the app's own fetch handler in-process, hitting
 * /api/cron/deliveries with the CRON_SECRET header, which is the exact
 * same code path an external scheduler would take over HTTPS.
 */

interface Env {
  CRON_SECRET?: string;
  NEXT_PUBLIC_SITE_URL?: string;
}

type WorkerExport = {
  fetch: (req: Request, env: Env, ctx: unknown) => Promise<Response>;
};

// Built by the OpenNext adapter, not tracked in git. The ts-ignore keeps
// plain clones (which have not run the Workers build yet) typechecking.
// @ts-ignore generated by npx opennextjs-cloudflare build
import worker from "./.open-next/worker.js";

const handler = worker as unknown as WorkerExport;

const entry = {
  fetch(req: Request, env: Env, ctx: unknown): Promise<Response> {
    return handler.fetch(req, env, ctx);
  },

  async scheduled(_controller: unknown, env: Env, ctx: unknown): Promise<void> {
    const base = env.NEXT_PUBLIC_SITE_URL ?? "https://pandamessages.com";
    const headers: Record<string, string> = {};
    if (env.CRON_SECRET) {
      headers.Authorization = `Bearer ${env.CRON_SECRET}`;
    }
    const req = new Request(new URL("/api/cron/deliveries", base), { headers });
    try {
      const res = await handler.fetch(req, env, ctx);
      if (!res.ok) {
        console.error(`cron tick failed: HTTP ${res.status}`);
      }
    } catch (err) {
      console.error("cron tick threw", err);
    }
  },
};

export default entry;
